=== bernhardzosel/event-log-analyzer/event_log_analyzer/config_format.schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "path": {
      "type": "string"
    },
    "separator": {
      "type": ["string", "null"]
    },
    "event_log_format": {
      "type": "string",
      "enum": [
        "atomic",
        "interval"
      ]
    },
    "sorted": {
      "type": "boolean"
    },
    "row_id_column": {
      "type": ["string", "null"]
    },
    "job_column": {
      "type": ["string", "null"]
    },
    "machine_column": {
      "type": ["string", "null"]
    },
    "resource_columns": {
      "type": ["null","array"],
      "items": [
        {
          "type": "string"
        }
      ]
    },
    "transaction_type_column": {
      "type": ["string", "null"]
    },
    "time_attributes": {
      "type": "array",
      "items": [
        {
          "type": "string"
        }
      ]
    },
    "relative_time": {
      "type": "boolean"
    },
    "time_format": {
      "type": "string"
    },
    "activity_instance_column": {
      "type": ["string", "null"]
    },
    "group_attributes": {
      "type": ["null","array"],
      "items": [
        {
          "type": "string"
        }
      ]
    },


    "start_transaction_types": {
      "type": ["null","array"],
      "items": [
        {
          "type": "string"
        }
      ]
    },
    "complete_transaction_types": {
      "type": ["null","array"],
      "items": [
        {
          "type": "string"
        }
      ]
    }
  },
  "required": [
    "path",
    "event_log_format",
    "sorted",
    "row_id_column",
    "job_column",
    "machine_column",
    "resource_columns",
    "transaction_type_column",
    "time_attributes",
    "relative_time",
    "time_format",
    "activity_instance_column",
    "group_attributes",


    "start_transaction_types",
    "complete_transaction_types"
  ]
}

=== bernhardzosel/event-log-analyzer/test/data/event_log.json
{
    "path": "test/data/event_log.csv",
    "separator" : ";",
    "event_log_format" : "atomic",
    "sorted" : true,    
    "row_id_column" : null,   
    "job_column" : "Job",            
    "machine_column" : "Machine",   
    "resource_columns" : [
        "Resource"
    ],     
    "transaction_type_column" : "Transaction_Type", 
    "time_attributes": [
        "Timestamp"
    ],
    "relative_time" : true,
    "time_format" : "%H:%M:%S",
    "activity_instance_column" : null,
    "group_attributes" : [
        "Job",
        "Machine",
        "Resource"
    ],
    
    "start_transaction_types" : [
        "start"
    ],
    "complete_transaction_types" : [
        "complete"
    ]
}

=== bernhardzosel/event-log-analyzer/test/data/xes_gen_event_log.json
{
    "path" : "test/data/xes_gen_event_log.xes",    
    "event_log_format" : "atomic",
    "separator" : null,
    "sorted" : false,
    "row_id_column" : null,
    "job_column" : "Job",
    "machine_column" : "Machine",
    "resource_columns" : [
        "Resource"
    ],    
    "transaction_type_column" : "Transaction_Type",
    "time_attributes" : [
        "Timestamp"
    ],
    "relative_time" : false,
    "time_format" : "%Y-%m-%d %H:%M:%S",
    "activity_instance_column" : null,
    "group_attributes" : [
        "Job",
        "Machine",
        "Resource"
    ],
    "start_transaction_types" : [
        "start"
    ],
    "complete_transaction_types" : [
        "complete"
    ]    
}

=== bernhardzosel/event-log-analyzer/test/data/interval_log.json
{
    "path" : "test/data/interval_log.csv",    
    "event_log_format" : "interval",
    "separator" : ";",
    "sorted" : false,
    "row_id_column" : null,
    "job_column" : "Job",
    "machine_column" : "Machine",
    "resource_columns" : [
        "Resource"
    ],    
    "transaction_type_column" : null,
    "time_attributes" : [
        "Start",
        "End"
    ],
    "relative_time" : true,
    "time_format" : "%H:%M:%S",
    "activity_instance_column" : null,
    "group_attributes" : [
        "Job",
        "Machine",
        "Resource"
    ],
    "start_transaction_types" : [
    ],
    "complete_transaction_types" : [
    ]    
}

=== bernhardzosel/event-log-analyzer/test/data/production_data.json
{
    "path": "test/data/production_data.csv",
    "event_log_format" : "interval",
    "separator" : ";", 
    "sorted" : false,   
    "row_id_column" : "Row_ID",   
    "job_column" : "Case ID",            
    "machine_column" : "Resource",   
    "resource_columns" : [
        "Worker ID"
    ],     
    "transaction_type_column" : null, 
    "time_attributes": [
        "Start Timestamp",
        "Complete Timestamp"
    ],
    "relative_time" : false,
    "time_format" : "%Y/%m/%d %H:%M:%S.%f",
    "activity_instance_column" : null,
    "group_attributes" : [
        "Job",
        "Machine"
    ],
    
    "start_transaction_types" : [
    ],
    "complete_transaction_types" : [
    ]
}
